version: '3'

services:
  frontend:
    build:
      
      context: .
      dockerfile: Dockerfile
    image: sandeepsp21/mishi:1
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - frontend
    command: certonly --webroot --webroot-path=/var/www/html --email prabhusandeep31@gmail.com --agree-tos --no-eff-email --staging -d mishitest.com  -d www.mishitest.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /Users/sandeepprabhu/Desktop/mishipay/mish-app/
      o: bind

networks:
  app-network:
    driver: bridge